image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  - yarn install

build:
  stage: build
  tags:
    - docker
    - linux
  script:
    - yarn build

deploy:
  stage: deploy
  tags:
    - docker
    - linux
  script:
    - yarn semantic-release
  only:
    - master

